### ISSUE TITLE
Demo data

### ISSUE THREAD

**Issue by VincentSC** [tranduyhung/grav-theme-appi#6]
Is the demo-data available somewhere, so I can understand how to use the theme correctly?

**Comment by tranduyhung** [comment]
> Is the demo-data available somewhere, so I can understand how to use the theme correctly?

You can get the skeleton here: https://github.com/tranduyhung/grav-skeleton-appi

**Comment by VincentSC** [comment]
Thanks! Now I learned what "skeleton" means. :) See also your email
